---
title: "Creating subgroups"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
```


## Loading data

```{r}
ortho_data <- read_csv(here("Data", "2025_04_10_Ortho_Data.csv"))
```

## Creating group variable

```{r}

# Vectors of participant IDs for each group
td_ids <- c("c141097", "c143113", "c143114", "c143278", "c171014", "c171064", "c171071", "c171080",
            "c171082", "c171113", "c171129", "c171133", "c171141", "c171144", "c191018", "c191020",
            "c191021", "c191025", "c191031", "c191034", "c191035", "c191036", "c191060")

compensated_ids <- c("c194005", "c194010", "c194017", "c194018", "c194019", "c194020", "c194022", 
                     "c194025", "c194026", "c194027", "c194028", "c194029", "c194031", "c194035", 
                     "c194038", "c194039", "c194045", "c194047")

dyslexia_ids <- c("c194001", "c194002", "c194003", "c194004", "c194006", "c194007", "c194008", 
                  "c194009", "c194011", "c194013", "c194014", "c194016", "c194021", "c194023", 
                  "c194030", "c194032", "c194033", "c194034", "c194036", "c194040", "c194041", 
                  "c194042", "c194043", "c194046", "c194048", "c194049", "c194051", "c194055", 
                  "c194057", "c194058")

# Assign groups
ortho_data <- ortho_data %>%
  mutate(Group = case_when(
    participant_id %in% td_ids ~ "TD",
    participant_id %in% compensated_ids ~ "Compensated",
    participant_id %in% dyslexia_ids ~ "Dyslexia",
    TRUE ~ NA_character_
  ))

```


## Viewing IDs that are in each group

```{r}
## TD
ortho_data %>%
  filter(Group == "TD") %>%
  select(participant_id) %>%
  distinct()
```

```{r}
## Compensated
ortho_data %>%
  filter(Group == "Compensated") %>%
  select(participant_id) %>%
  distinct()
```


```{r}
## Dyslexia
ortho_data %>%
  filter(Group == "Dyslexia") %>%
  select(participant_id) %>%
  distinct()
```





```{r}
## Viewing IDs that are NAs

ortho_data %>%
  filter(is.na(Group)) %>%
  select(participant_id) %>%
  distinct()
```



```{r}
ortho_data_clean <- ortho_data %>%
  filter(!is.na(Group))
```

## Extracting Data

```{r}
write_csv(ortho_data_clean, "2025_04_10_Ortho_Data_with_groups.csv")
```





























